### ISSUE TITLE
Basic user@pass is dropped (worked  in 2.6.1)

### ISSUE THREAD

**Issue by GrosSacASac** [node-fetch/node-fetch#1330]
I didn't see it mentioned in the upgrade guide

**Reproduction**

1. Create an url that contains a user and password
2. use fetch
3. look at what was sent

```js
import fetch from "node-fetch";

if (!globalThis.fetch) {
    globalThis.fetch = fetch;
}


const baseUrl = `https://XXX:YYY@letz.social/echo-test/zzz`;

fetch(baseUrl, {
    headers: {
        Accept: `application/json`,
    },
}).then(response => {
    if(!response.ok) {
        throw response.statusText;
    }
    return response.text();
}).then(text => {
    console.log(text);
});
```
**Observed behavior (3.0.0)**

```
node test.js
/echo-test/zzz    Method: GET

    Headers:

Host: letz.social
X-IP: 94.252.80.148
Connection: close
accept: application/json
accept-encoding: gzip,deflate,br
user-agent: node-fetch

    Body:
```
**Expected behavior (2.6.5)**

```
node test.js      
/echo-test/zzz    Method: GET

    Headers:

Host: letz.social
X-IP: 94.252.80.148
Connection: close
Accept: application/json
User-Agent: node-fetch/1.0 (+https://github.com/bitinn/node-fetch)
Accept-Encoding: gzip,deflate
Authorization: Basic WFhYOllZWQ==

    Body:


```

**Screenshots**

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | 3.0.0
| node             | 16
| npm              |
| Operating System |

**Additional context**

https://letz.social/echo-test/xyz is a simple  echo http server 
https://github.com/GrosSacASac/echo-http-node
