### ISSUE TITLE
Question: 

### ISSUE THREAD

**Issue by ruslanx3m** [node-fetch/node-fetch#914]
Need help, I do some mistake .. can someone check if code is correct ? copied code from chrome devtools and modified.. 

**form** and cookies is **generated** by me..

```
const fetch = require("node-fetch");


const url = '';
const form = '';
const cookies = '';

const opt = {
    "headers": {
        "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
        "accept-language": "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7",
        "cache-control": "no-cache",
        "content-type": "application/x-www-form-urlencoded",
        "pragma": "no-cache",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-origin",
        "sec-fetch-user": "1",
        "upgrade-insecure-requests": "1",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
        "cookie": cookies
    },
    "referrer": url ,
    "referrerPolicy": "no-referrer-when-downgrade",
    "body": form,
    "method": "POST",
    "mode": "cors"
};

const postResponse = await fetch(url, opt);

if (postResponse.ok) {
    post_body = await postResponse.text();
    post_cookies = await postResponse.headers.raw()['set-cookie'];
    console.log(post_body);
}
```

.. or how correctly post this form data:

```
        __EVENTTARGET: 
         __EVENTARGUMENT: 
         __LASTFOCUS: 
         __VIEWSTATE: gdfgdfgdfgdfg
         __VIEWSTATEGENERATOR: 654654
         __VIEWSTATEENCRYPTED: 
         __EVENTVALIDATION: 
         ctl00$ddlWersjeJezykowe: 99
         ctl00$cp$NoBotID$NoBotID_NoBotExtender_ClientState: 
         recaptcha_response_field: 
         ctl00$cp$Captcha$ctl01$tbAnswer: 88
         ctl00$cp$Captcha$hAnswer: 88
         ctl00$cp$btnDalej: Button
```

Node v12
